VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IHeaderLookupImplementation"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' Version 1.1.1

'@Folder("CodeBase.Classes.Drivers.Interfaces")

Option Explicit

Public Property Get OldHeader(ByVal InputHeader As String, ByVal ReturnKey As Boolean)

End Property

Public Property Get NewHeader(ByVal InputHeader)

End Property
